CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY, FULL_NAME VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100), "PASSWORD" VARCHAR(100), "TYPE" INT, BALANCE DECIMAL(10, 2), "VERSION" BIGINT
);

-- UM CPF E UM EMAIL SÓ PODE TER UMA CARTEIRA
-- CAMADA DE SEGURANÇA LIMITADA PELO BANCO
-- CRITÉRIO DE UNICIDADE...
-- GARANTE AS REGRAS DE NEGOCIO
CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    "VALUE" DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID), -- UMA CARTEIRA PODE TER VARIAS TRANSAÇÕES
    FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID) -- CHAVE ESTRANGEIRA COM A WALLET
);